### ISSUE TITLE
Type theory reading group

### ISSUE THREAD

**Issue by vikraman** [wonks/wonks.github.io#17]
I would like to move teh type theory reading group website here, for visibility, if that is agreeable. I would prefer it to be at `wonks.github.io/type-theory-reading-group`, so I need a repository. I realized I'm not a member of the wonks github org yet.

Edit: ping @frenchy64

**Comment by frenchy64** [comment]
I'm not an admin of the wonks org, I'll bug Tori about it tomorrow.

**Comment by vikraman** [comment]
Turns out @cgswords is the admin.

**Comment by cgswords** [comment]
1. IIRC, any member can edit this website. You don't need admin powers, just membership in the wonks group (e.g., akuhlens recently creating the MWPLS page here). It appears that @vikraman isn't currently a member of the wonks group. I sent an invite. **It may be worthwhile to get people invited as part of PL onboarding in the future.**

2. There are a bunch of people with admin powers, including @Victorialewis and many faculty members. I've also given admin powers to @frenchy64 as of now. Sorry that didn't happen sooner.
