### ISSUE TITLE
Add these people to the page

### ISSUE THREAD

**Issue by rrnewton** [wonks/wonks.github.io#2]
Awesome new site!  

Let's add:

 * Trevor to the postdoc list!  -- I'll harass him to put an IU site up (@tmcdonell), but [here's his UNSW one](http://www.cse.unsw.edu.au/~tmcdonell/site/index.html)

 * Buddhika Chamith to the grad student list -- @chamibuddhika, put up full professional website too! In addition [to your linkedIn](https://www.linkedin.com/in/buddhikachamith)
 * Ali Varamesh to the grad student list (@alivaramesh -- ditto, [LinkedIn here](https://www.linkedin.com/pub/ali-varamesh/47/5b6/6))
 * Peter Fogg to the grad student list (@peter-fogg)
 * Michael Vollmer to the grad student list (@vollmerm)
 * Ömer Sinan Ağacan to the grad student list (@osa1)
 * 

Likewise, Roshan finalized his Ph.D. right?  

And it looks like Ed Amsden should move to the "Former members" category.  And Aaron Todd should be on there as well -- he may have a website or linkedin page to link too.

**Comment by rrnewton** [comment]
If you want to be really thorough you could list "former faculty" as well -- Amal, etc, and link their pages.

**Comment by cgswords** [comment]
[ ] Trevor Mcdonell
[ ] Buddhika Chamith
[ ] Ali Varamesh
[ ] Peter Fogg
[ ] Michael Vollmer
[ ] Omer Agacan

I don't know if Roshan has finalized his Ph.D.

**Comment by cgswords** [comment]
I think I got everyone except for that Roshan thing. I'm leaving off former faculty for now, because that's a slippery slope. Closing this issue.
