### ISSUE TITLE
main web page out-of-date

### ISSUE THREAD

**Issue by jsiek** [wonks/wonks.github.io#26]
Is anyone maintaining this site anymore?

**Comment by cangiuli** [comment]
Can I say "someone should" without volunteering to be the new maintainer in perpetuity? :) I am willing to pitch in.

**Comment by cangiuli** [comment]
Since my previous comment I've made a lot of changes throughout to clean up the website and bring it up to date(ish). There's more that can/should be done but it's a lot better now. Thanks to the previous maintainers for setting up all the infrastructure!
